version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_backend
    ports:
      - "10001:10001"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: llm_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - API_URL=http://backend:10001

